workflow:
  # NOTE: only run the pipeline when pushing a commit/tag/branch, or when
  # creating the pipeline in the UI.
  # This allows to avoid duplicated pipelines in merge requests.
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api"

stages:
  - dryrun
  - setup
  - environments

.common_rules_tag: &common_rules_tag
  - if: $CI_COMMIT_TAG
  # NOTE: set the variable below at your own risk.
  # Setting this forces a tag pipeline, it can be done when git-pushing:
  # git push -o ci.variable="FORCE_CI_COMMIT_TAG=..." -o ci.variable="FORCE_CI_COMMIT_SHORT=..."
  - if: $FORCE_CI_COMMIT_TAG

# NOTE: the general workflow for changing this is to manually create a pipeline.
# See https://www.grid5000.fr/w/TechTeam:Environment-recipes.
# Alternatively you can *temporarily* hardcode some values here, while working
# on something specific. Remember to remove the commit ;)
variables:
  REFREPO_BRANCH:
    description: The refrepo branch you want to use for the pipeline
    value: master
  ENVIRONMENTS:
    description: A regexp of environments to build
  CLUSTERS:
    description: The coma separated list of clusters to test automatically
  ENABLE_UNUSED_GEN_JOBS:
    description: Should non-matching generation job be created? Leave blank to avoid generation.
  ENABLE_UNUSED_TEST_JOBS:
    description: Should non-matching test job be created? Leave blank to avoid generation.
  ENVIRONMENTS_LIST:
    description: An explicit list of environments to build
  CUSTOM_POSTINSTALL_BRANCH:
    description: An optional postinstall branch to use instead of the released one.


upload-custom-postinstall:
  stage: setup
  needs: []
  tags:
    - grid5000-shell
  rules:
    - if: '$CUSTOM_POSTINSTALL_BRANCH != ""'
  script:
    - ci/gitlab/make_postinstall_available.sh -b ${CUSTOM_POSTINSTALL_BRANCH} -f "${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}"

clone-refrepo:
  stage: setup
  image: ${CI_REGISTRY}/grid5000/docker/g5k-debian:bullseye
  tags:
    - grid5000-docker
  needs:
    - job: upload-custom-postinstall
      optional: true
  rules:
    # If variables are filled then just start, otherwise wait for user input.
    - if: '$ENVIRONMENTS != "" || $CLUSTERS != "" || $ENVIRONMENTS_LIST != ""'
    - *common_rules_tag
    # There is no alternative, we don't show up the job if these variables are
    # not set. Read the documentation in TechTeam:Environment-recipes to learn
    # about manually creating a pipeline for this.
  script:
    - echo ${REFREPO_BRANCH}
    - git clone https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.inria.fr/grid5000/reference-repository.git --depth 1 -b ${REFREPO_BRANCH}
  artifacts:
    paths:
      - reference-repository

.pipeline-generation:
  stage: setup
  image: ${CI_REGISTRY}/grid5000/docker/g5k-debian:bullseye
  tags:
    - grid5000-docker
  needs:
    - clone-refrepo
  variables:
    RUBYLIB: reference-repository/lib
  before_script:
    - rm -rf generated && mkdir generated
  artifacts:
    paths:
      - generated

# NOTE: this is a standalone job because gitlab requires <5MB artifacts for
# dynamic child pipelines.
gen-child-pipelines:
  extends: .pipeline-generation
  rules:
    - if: '$ENVIRONMENTS != "" || $CLUSTERS != "" || $ENVIRONMENTS_LIST != ""'
  script:
    - ruby ci/gitlab/gen_jobs.rb -o generated

gen-tag-pipeline:
  extends: .pipeline-generation
  rules:
    - *common_rules_tag
  script:
    # NOTE: both these if are here to simulate a tag pipeline with an arbitrary
    # commit and an arbitrary tag.
    - |
      if [ -n "${FORCE_CI_COMMIT_TAG}" ]; then
        export CI_COMMIT_TAG="${FORCE_CI_COMMIT_TAG}"
      fi
    - |
      if [ -n "${FORCE_CI_COMMIT_SHORT}" ]; then
        export CI_COMMIT_SHORT_SHA="${FORCE_CI_COMMIT_SHORT}"
      fi
    - echo $CI_COMMIT_TAG
    - echo $CI_COMMIT_SHORT_SHA
    - ruby ci/gitlab/push/gen_jobs_tag.rb -o generated -t $CI_COMMIT_TAG -c $CI_COMMIT_SHORT_SHA

environments-pipeline:
  stage: environments
  needs:
    - gen-child-pipelines
  rules:
    - if: '$ENVIRONMENTS != "" || $CLUSTERS != "" || $ENVIRONMENTS_LIST != ""'
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
    ROOT_POSTINSTALL_BRANCH: $CUSTOM_POSTINSTALL_BRANCH
  trigger:
    strategy: depend
    include:
      - artifact: generated/main.yml
        job: gen-child-pipelines

push-environments-pipeline:
  stage: environments
  needs:
    - gen-tag-pipeline
  rules:
    - *common_rules_tag
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  trigger:
    strategy: depend
    include:
      - artifact: generated/main-tag.yml
        job: gen-tag-pipeline

include:
  - 'ci/gitlab/sanity.yml'
